module.exports = {
  apps: [
    {
      name: 'lzti',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '/home/pupeng/projects/lzti',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 3000,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/error.log',
      out_file: './logs/out.log',
      log_file: './logs/combined.log',
      time: true,
    },
    {
      name: 'wxcl-v2',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '/home/pupeng/projects/wxcl-v2',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 3000,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        PORT: 3006,
      },
      error_file: './logs/wxcl-error.log',
      out_file: './logs/wxcl-out.log',
      log_file: './logs/wxcl-combined.log',
      time: true,
    },
  ],
};
